"""Shared MCP timeout defaults."""

MCP_REQUEST_TIMEOUT_SEC = 30.0
MCP_ELICITATION_TIMEOUT_SEC = 300.0
MCP_TOOL_CALL_REQUEST_TIMEOUT_SEC = (
    MCP_ELICITATION_TIMEOUT_SEC + MCP_REQUEST_TIMEOUT_SEC
)
MCP_TOOL_CALL_TIMEOUT_SEC = (
    MCP_TOOL_CALL_REQUEST_TIMEOUT_SEC + MCP_REQUEST_TIMEOUT_SEC
)
