"""TaskflowState to PlanDraft compiler.

Source: ``docs/文档.md`` Sections 5.5, 5.6, 5.7, and 5.8. The compiler is
pure: it reads TaskflowState and ProjectState and produces a PlanDraft. Service
code decides when to persist WorkItems, GoalWorkLinks, TraceLinks, and TaskRuns.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any

from labrastro_server.taskflow.domain.time import utc_now
from labrastro_server.taskflow.domain.project_state import (
    GoalWorkLink,
    GoalWorkRelationType,
    ProjectState,
    TraceEntityType,
    TraceLink,
    TraceRelationType,
    WorkItem,
    WorkItemType,
)
from labrastro_server.taskflow.domain.taskflow_state import (
    ConfirmationState,
    RiskRecord,
    ScenarioRecord,
    TaskflowState,
    WorkItemCandidate,
)


def _new_id(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex}"


def _normalize(value: str) -> str:
    return "-".join(value.lower().strip().split())


@dataclass(slots=True)
class CompiledWorkItemCandidate:
    """Compiler decision for one candidate WorkItem."""

    candidate_id: str
    title: str
    description: str
    type: str
    action: str
    work_item_id: str
    reuse_work_item_id: str | None = None
    dedupe_key: str | None = None
    relation_type: str = GoalWorkRelationType.DIRECT_DELIVERY.value
    rationale: str = ""
    acceptance_refs: list[str] = field(default_factory=list)
    decision_refs: list[str] = field(default_factory=list)
    artifact_refs: list[str] = field(default_factory=list)
    scenario_refs: list[str] = field(default_factory=list)
    risk_refs: list[str] = field(default_factory=list)
    depends_on: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "title": self.title,
            "description": self.description,
            "type": self.type,
            "action": self.action,
            "work_item_id": self.work_item_id,
            "reuse_work_item_id": self.reuse_work_item_id,
            "dedupe_key": self.dedupe_key,
            "relation_type": self.relation_type,
            "rationale": self.rationale,
            "acceptance_refs": list(self.acceptance_refs),
            "decision_refs": list(self.decision_refs),
            "artifact_refs": list(self.artifact_refs),
            "scenario_refs": list(self.scenario_refs),
            "risk_refs": list(self.risk_refs),
            "depends_on": list(self.depends_on),
            "metadata": dict(self.metadata),
        }


@dataclass(slots=True)
class PlanDraft:
    """Intermediate plan generated by compiling one TaskflowState."""

    id: str
    taskflow_id: str
    project_id: str
    goal_id: str
    objective: str
    scope: dict[str, list[str]]
    work_item_candidates: list[CompiledWorkItemCandidate] = field(default_factory=list)
    goal_work_links: list[GoalWorkLink] = field(default_factory=list)
    decision_work_links: list[TraceLink] = field(default_factory=list)
    acceptance_trace_links: list[TraceLink] = field(default_factory=list)
    future_goal_candidates: list[str] = field(default_factory=list)
    risks: list[dict[str, Any]] = field(default_factory=list)
    assumptions: list[dict[str, Any]] = field(default_factory=list)
    unresolved_questions: list[dict[str, Any]] = field(default_factory=list)
    created_at: str = field(default_factory=utc_now)
    compiler_version: str = "plan_compiler.v1"

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "taskflow_id": self.taskflow_id,
            "project_id": self.project_id,
            "goal_id": self.goal_id,
            "objective": self.objective,
            "scope": {key: list(value) for key, value in self.scope.items()},
            "work_item_candidates": [
                candidate.to_dict() for candidate in self.work_item_candidates
            ],
            "goal_work_links": [link.to_dict() for link in self.goal_work_links],
            "decision_work_links": [
                link.to_dict() for link in self.decision_work_links
            ],
            "acceptance_trace_links": [
                link.to_dict() for link in self.acceptance_trace_links
            ],
            "future_goal_candidates": list(self.future_goal_candidates),
            "risks": [dict(item) for item in self.risks],
            "assumptions": [dict(item) for item in self.assumptions],
            "unresolved_questions": [dict(item) for item in self.unresolved_questions],
            "created_at": self.created_at,
            "compiler_version": self.compiler_version,
        }


class PlanCompiler:
    """Compile a TaskflowState into a traceable PlanDraft."""

    def compile(self, taskflow_state: TaskflowState, project_state: ProjectState) -> PlanDraft:
        """Compile candidates, reuse decisions, and trace links.

        Logic from ``docs/文档.md`` Section 5.5:
        TaskflowState plus ProjectState baseline produce work item candidates,
        goal_work_links, decision_work_links, acceptance_trace_links, and
        future_goal_candidates.
        """

        candidates = self._candidate_pool(taskflow_state)
        compiled_candidates: list[CompiledWorkItemCandidate] = []
        goal_links: list[GoalWorkLink] = []
        decision_links: list[TraceLink] = []
        acceptance_links: list[TraceLink] = []

        for candidate in candidates:
            compiled = self._compile_candidate(candidate, taskflow_state, project_state)
            compiled_candidates.append(compiled)

            # Logic from docs/文档.md Section 5.8: every Goal/WorkItem relation
            # is explicit, even when the WorkItem is reused.
            goal_links.append(
                GoalWorkLink(
                    id=_new_id("goal-work-link"),
                    project_id=taskflow_state.meta.project_id,
                    goal_id=taskflow_state.meta.goal_id,
                    work_item_id=compiled.work_item_id,
                    relation_type=compiled.relation_type,
                    rationale=compiled.rationale,
                    acceptance_refs=compiled.acceptance_refs,
                    decision_refs=compiled.decision_refs,
                )
            )

            for decision_ref in compiled.decision_refs:
                decision_links.append(
                    TraceLink(
                        id=_new_id("trace"),
                        project_id=taskflow_state.meta.project_id,
                        source_type=TraceEntityType.DECISION,
                        source_id=decision_ref,
                        target_type=TraceEntityType.WORK_ITEM,
                        target_id=compiled.work_item_id,
                        relation_type=TraceRelationType.IMPLEMENTS,
                        rationale=f"Decision {decision_ref} shapes {compiled.title}.",
                    )
                )
            for acceptance_ref in compiled.acceptance_refs or compiled.scenario_refs:
                acceptance_links.append(
                    TraceLink(
                        id=_new_id("trace"),
                        project_id=taskflow_state.meta.project_id,
                        source_type=TraceEntityType.ACCEPTANCE_EXAMPLE,
                        source_id=acceptance_ref,
                        target_type=TraceEntityType.WORK_ITEM,
                        target_id=compiled.work_item_id,
                        relation_type=TraceRelationType.VALIDATES,
                        rationale=f"Acceptance/scenario {acceptance_ref} validates {compiled.title}.",
                    )
                )

        return PlanDraft(
            id=_new_id("plan-draft"),
            taskflow_id=taskflow_state.meta.taskflow_id,
            project_id=taskflow_state.meta.project_id,
            goal_id=taskflow_state.meta.goal_id,
            objective=taskflow_state.intent.goal_statement,
            scope={
                "in": list(taskflow_state.intent.scope_in),
                "out": list(taskflow_state.intent.scope_out),
                "deferred": list(taskflow_state.intent.deferred_scope),
                "success_criteria": list(taskflow_state.intent.success_criteria),
            },
            work_item_candidates=compiled_candidates,
            goal_work_links=goal_links,
            decision_work_links=decision_links,
            acceptance_trace_links=acceptance_links,
            future_goal_candidates=list(taskflow_state.delivery.future_goal_candidates),
            risks=[risk.to_dict() for risk in taskflow_state.design.risks],
            assumptions=[
                assumption.to_dict()
                for assumption in taskflow_state.clarification.assumptions
            ],
            unresolved_questions=[
                question.to_dict()
                for question in taskflow_state.clarification.open_questions
                if not question.answered
            ],
        )

    def _compile_candidate(
        self,
        candidate: WorkItemCandidate,
        state: TaskflowState,
        project: ProjectState,
    ) -> CompiledWorkItemCandidate:
        dedupe_key = candidate.dedupe_key or self._dedupe_key(state, candidate)

        # Logic from docs/文档.md Section 5.6: exact logical delivery match
        # reuses a WorkItem, while dispatch still creates a fresh TaskRun later.
        reusable = project.find_work_item_by_dedupe_key(dedupe_key)
        if reusable is not None:
            return self._compiled_from_reuse(candidate, reusable, dedupe_key)

        similar = project.find_similar_work_items(
            title=candidate.title, type=candidate.type.value
        )
        if similar and candidate.acceptance_refs:
            base = similar[0]
            return self._compiled_from_new(
                candidate,
                dedupe_key,
                derived_from=base.id,
                rationale=(
                    "Similar title/type found, but acceptance boundary is distinct; "
                    "create derived WorkItem."
                ),
            )

        return self._compiled_from_new(
            candidate,
            dedupe_key,
            rationale="No reusable WorkItem matched the dedupe key.",
        )

    def _compiled_from_reuse(
        self, candidate: WorkItemCandidate, item: WorkItem, dedupe_key: str
    ) -> CompiledWorkItemCandidate:
        return CompiledWorkItemCandidate(
            candidate_id=candidate.id,
            title=candidate.title,
            description=candidate.description,
            type=candidate.type.value,
            action="reuse",
            work_item_id=item.id,
            reuse_work_item_id=item.id,
            dedupe_key=dedupe_key,
            relation_type=candidate.relation_type.value,
            rationale="Existing WorkItem matched the compiler dedupe key.",
            acceptance_refs=list(candidate.acceptance_refs or item.acceptance_refs),
            decision_refs=list(candidate.decision_refs or item.decision_refs),
            artifact_refs=list(candidate.artifact_refs or item.artifact_refs),
            scenario_refs=list(candidate.scenario_refs),
            risk_refs=list(candidate.risk_refs),
            depends_on=list(candidate.depends_on or item.depends_on),
            metadata=dict(candidate.metadata),
        )

    def _compiled_from_new(
        self,
        candidate: WorkItemCandidate,
        dedupe_key: str,
        *,
        derived_from: str | None = None,
        rationale: str,
    ) -> CompiledWorkItemCandidate:
        depends_on = list(candidate.depends_on)
        if derived_from and derived_from not in depends_on:
            depends_on.append(derived_from)
        return CompiledWorkItemCandidate(
            candidate_id=candidate.id,
            title=candidate.title,
            description=candidate.description,
            type=candidate.type.value,
            action="create",
            work_item_id=f"work-{candidate.id}",
            reuse_work_item_id=None,
            dedupe_key=dedupe_key,
            relation_type=candidate.relation_type.value,
            rationale=rationale,
            acceptance_refs=list(candidate.acceptance_refs),
            decision_refs=list(candidate.decision_refs),
            artifact_refs=list(candidate.artifact_refs),
            scenario_refs=list(candidate.scenario_refs),
            risk_refs=list(candidate.risk_refs),
            depends_on=depends_on,
            metadata={"derived_from": derived_from, **dict(candidate.metadata)},
        )

    def _candidate_pool(self, state: TaskflowState) -> list[WorkItemCandidate]:
        if state.outputs.work_item_candidates:
            return list(state.outputs.work_item_candidates)
        generated: list[WorkItemCandidate] = []
        for scenario in state.clarification.scenarios:
            generated.append(self._candidate_from_scenario(state, scenario))
        for risk in state.design.risks:
            if risk.impact == "high":
                generated.append(self._candidate_from_risk(state, risk))
        return generated

    def _candidate_from_scenario(
        self, state: TaskflowState, scenario: ScenarioRecord
    ) -> WorkItemCandidate:
        return WorkItemCandidate(
            id=f"scenario-{scenario.id}",
            title=f"Implement scenario: {scenario.title}",
            description="\n".join([*scenario.given, *scenario.when, *scenario.then]),
            type=WorkItemType.IMPLEMENTATION,
            scenario_refs=[scenario.id],
            dedupe_key=f"{state.meta.project_id}:implementation:{_normalize(scenario.title)}",
        )

    def _candidate_from_risk(
        self, state: TaskflowState, risk: RiskRecord
    ) -> WorkItemCandidate:
        return WorkItemCandidate(
            id=f"risk-{risk.id}",
            title=f"Mitigate risk: {risk.statement}",
            description=risk.mitigation or risk.statement,
            type=WorkItemType.RESEARCH,
            risk_refs=[risk.id],
            dedupe_key=f"{state.meta.project_id}:research:{_normalize(risk.statement)}",
        )

    def _dedupe_key(self, state: TaskflowState, candidate: WorkItemCandidate) -> str:
        """Build the baseline dedupe key from docs/文档.md Section 5.6 signals."""

        parts = [
            state.meta.project_id,
            candidate.repo_ref or "",
            candidate.workspace_ref or "",
            candidate.type.value,
            _normalize(candidate.title),
            ",".join(sorted(candidate.acceptance_refs)),
            ",".join(sorted(candidate.decision_refs)),
            ",".join(sorted(candidate.artifact_refs)),
        ]
        return ":".join(part for part in parts if part)


__all__ = ["CompiledWorkItemCandidate", "PlanCompiler", "PlanDraft"]
