"""Auth persistence interfaces."""

from __future__ import annotations

from typing import Any, Protocol

from labrastro_server.services.auth.models import (
    AccessTokenRecord,
    AuthDevice,
    AuthUser,
    LoginFailureRecord,
    RefreshTokenRecord,
)


class AuthStore(Protocol):
    def get_user_by_username(self, username: str) -> AuthUser | None: ...
    def get_user_by_id(self, user_id: str) -> AuthUser | None: ...
    def list_users(self) -> list[AuthUser]: ...
    def upsert_user(self, user: AuthUser) -> AuthUser: ...
    def update_user(self, user: AuthUser) -> AuthUser: ...
    def create_device(self, device: AuthDevice) -> AuthDevice: ...
    def get_device(self, device_id: str) -> AuthDevice | None: ...
    def list_devices(self, *, user_id: str | None = None) -> list[AuthDevice]: ...
    def update_device(self, device: AuthDevice) -> AuthDevice: ...
    def record_refresh_token(self, token: RefreshTokenRecord) -> None: ...
    def get_refresh_token_by_hash(self, token_hash: str) -> RefreshTokenRecord | None: ...
    def update_refresh_token(self, token: RefreshTokenRecord) -> None: ...
    def list_refresh_tokens(
        self, *, user_id: str | None = None, device_id: str | None = None
    ) -> list[RefreshTokenRecord]: ...
    def revoke_refresh_tokens(
        self,
        *,
        user_id: str | None = None,
        device_id: str | None = None,
        revoked_at: float,
    ) -> int: ...
    def record_access_token(self, token: AccessTokenRecord) -> None: ...
    def get_access_token_by_hash(self, token_hash: str) -> AccessTokenRecord | None: ...
    def update_access_token(self, token: AccessTokenRecord) -> None: ...
    def revoke_access_tokens(
        self,
        *,
        user_id: str | None = None,
        device_id: str | None = None,
        exclude_device_id: str | None = None,
        revoked_at: float,
    ) -> int: ...
    def delete_expired_access_tokens(self, *, now: float) -> int: ...
    def record_login_failure(self, failure: LoginFailureRecord) -> None: ...
    def count_login_failures(
        self, *, username: str, source: str, since: float
    ) -> int: ...
    def clear_login_failures(self, *, username: str, source: str) -> int: ...
    def delete_old_login_failures(self, *, before: float) -> int: ...
    def append_audit_event(self, event: dict[str, Any]) -> None: ...
    def list_audit_events(
        self,
        *,
        limit: int = 100,
        after_created_at: float | None = None,
        event_type: str | None = None,
        user_id: str | None = None,
    ) -> list[dict[str, Any]]: ...
